### ISSUE TITLE
Store latest live log

### ISSUE THREAD

**Issue by BFergerson** [sourceplusplus/interface-jetbrains#612]
You can get a live log hit at a certain location, close the file, open the file, go back to live log status bar and now you're waiting for a live log again.

Example:
![Peek 2022-01-03 15-26](https://user-images.githubusercontent.com/3278877/147976892-454f7cb8-02cb-45eb-9630-088b7eb478f3.gif)

**Comment by javamak** [comment]
Hi, 
My approach to this problem  is below. Please suggest. 
Each instance of LogStatusBar contains commandModel attached with JTable. The command model contains an ArrayList which receives the data through Vertx events. This ArrayList can be moved to a new Map in LiveStatusManager paired with the logId as key. And always generate the commandModel ArrayList from this Map using log id. The problem with this approach is the data will grow if the log instruction never removed may be we can limit the max size of the ArrayList and remove old entries. Let me know if it doesn't make sense.

**Comment by BFergerson** [comment]
If by log id you mean `LiveLog.id`, I think that works. Limit the size to 100.
