### ISSUE TITLE
Missing command highlighting on partial text matches

### ISSUE THREAD

**Issue by BFergerson** [sourceplusplus/interface-jetbrains#620]
When searching for commands you have to input words fully for them to highlight:
![Peek 2022-01-04 19-13](https://user-images.githubusercontent.com/3278877/148140890-d45783be-d7af-489a-8763-195764692309.gif)

It should highlight even when you input partial words.

**Comment by javamak** [comment]
![controlbar_match](https://user-images.githubusercontent.com/20161375/148663594-c9d21f36-6e2d-48b0-8229-92896fbae723.gif)

Fix available as part of PR #618

**Comment by BFergerson** [comment]
@javamak, please don't work on multiple issues in one PR. I was going to mention that on https://github.com/sourceplusplus/interface-jetbrains/pull/617 but figured it was a one-time thing. Going forward, please separate them even if they are small changes or changes in the same file.
