### ISSUE TITLE
Fix command bar (dark mode) selection color

### ISSUE THREAD

**Issue by BFergerson** [sourceplusplus/interface-jetbrains#621]
Before the #598, the dark mode command selection looked as such:
![Peek 2022-01-04 19-33](https://user-images.githubusercontent.com/3278877/148142315-fca174a9-8c64-4763-b3b3-4699f2c79b67.gif)

Now it looks like:
![Peek 2022-01-04 19-27](https://user-images.githubusercontent.com/3278877/148141895-cbb72c62-4933-4ac0-839c-7be89e05ffe6.gif)

Also, dark mode selection is happening with `AutoCompleteField` in light mode:
![Peek 2022-01-04 19-25](https://user-images.githubusercontent.com/3278877/148141753-63d2a047-a232-4b27-9517-111f253c6da1.gif)

---

I've also noticed that the new command/status bars are lighter in dark mode than they used to be. I like the way it looks in light mode but I prefer the darker coloring in dark mode.

### Old
![Peek 2022-01-04 19-34](https://user-images.githubusercontent.com/3278877/148142371-2397d6a1-b4d6-44c1-aa9f-4c422385f1d2.gif)

### New
![Peek 2022-01-04 19-36](https://user-images.githubusercontent.com/3278877/148142535-0c6c81ad-8374-4024-a0ae-95ff5da3e8eb.gif)

**Comment by javamak** [comment]
![image](https://user-images.githubusercontent.com/20161375/149031520-67049e29-34ae-48f7-868e-14779922b394.png)
Changed the background color of Text field in all status bars to Black in dark mode. Should I reset for other controls also for dark mode?

**Comment by BFergerson** [comment]
Other controls like the hit limit and throttle? If so, yes please.
