### ISSUE TITLE
Editing live log that used ${} doesn't work correctly

### ISSUE THREAD

**Issue by BFergerson** [sourceplusplus/interface-jetbrains#629]
![Peek 2022-01-11 17-55](https://user-images.githubusercontent.com/3278877/149034485-c27bb50d-d49f-4bf9-b2d9-87367c500628.gif)

**Comment by BFergerson** [comment]
After you've completed https://github.com/sourceplusplus/interface-jetbrains/pull/655 start looking into this. I believe you might need to update `LiveLog` and the live-instrument-processor. I don't think there is enough information on the plugin to properly decide when to replace something with `$` or `${}`.

**Comment by javamak** [comment]
Found one more issue. The order of the variables are mixed if ${} variables present first in the log statement. looking into it
![629](https://user-images.githubusercontent.com/20161375/154813349-ad307f7f-86de-4885-bce9-846522dc9afe.gif)
