### ISSUE TITLE
The plugin settings interface is empty

### ISSUE THREAD

**Issue by Superskyyy** [sourceplusplus/interface-jetbrains#699]
Hello, I was trying out source++ and it looks like the plugin is not configurable in my IDEs.

I've tried it in IDEA and Pycharm, both show the following line when I follow the configuration doc. 
![image](https://user-images.githubusercontent.com/26076517/160667564-40284237-59b6-469b-96a4-824a1c9d4c63.png)

These are my versions:
![image](https://user-images.githubusercontent.com/26076517/160667799-594b0f0d-630b-4d58-8ec2-6e1fdfbfd9c9.png)

**Comment by BFergerson** [comment]
Sorry for such a blatant issue and thanks for trying this plugin out before the blog was published.

You can fix this issue by uninstalling the current version and re-installing the next version manually via the zip file: https://github.com/sourceplusplus/interface-jetbrains/suites/5849416807/artifacts/196855614

You can find instructions for manually installing plugins here: https://www.jetbrains.com/help/idea/managing-plugins.html#install_plugin_from_disk

**Comment by Superskyyy** [comment]
> Sorry for such a blatant issue and thanks for trying this plugin out before the blog was published.
> 
> You can fix this issue by uninstalling the current version and re-installing the next version manually via the zip file: [sourceplusplus/interface-jetbrains/suites/5849416807/artifacts/196855614](https://github.com/sourceplusplus/interface-jetbrains/suites/5849416807/artifacts/196855614)
> 
> You can find instructions for manually installing plugins here: [jetbrains.com/help/idea/managing-plugins.html#install_plugin_from_disk](https://www.jetbrains.com/help/idea/managing-plugins.html#install_plugin_from_disk)
> 
> Note: If you're connecting to an Apache SkyWalking server, you will need to include the port in the host setting (e.g. `http://localhost:12800`).

Thank you so much! That response was so quick, you are awesome!

**Comment by BFergerson** [comment]
Thanks for the confirmation. Let me know if you run into additional issues.
