### ISSUE TITLE
Python endpoint name detector

### ISSUE THREAD

**Issue by BFergerson** [sourceplusplus/interface-jetbrains#716]
`spp.jetbrains.marker.jvm.psi.EndpointDetector` is able to extract the endpoint name from Spring MVC annotations. For example, the following:
```java
import org.springframework.web.bind.annotation.RequestMapping;
public class TestController {
    @RequestMapping(value = "/doGet", method = RequestMethod.GET)
    public void doGet() {}
}
```

`EndpointDetector` will extract `GET:/doGet` as the endpoint name.

---

This task is to create the equivalent for Python Flask annotations such that:
```python
@app.route('/todos', methods=['GET'])
def get_todos():
    if len(todos) == 0:
        return jsonify([])
    return jsonify(list(todos.values()))
```

will extract `GET:/todos` as the endpoint name.

---

You can use https://github.com/sourceplusplus/tutorial-python/blob/master/app.py as a testing file.

Just determine the endpoint name for now. `EndpointDetector` also finds the endpoint id but that will be done after this task.

**Comment by BFergerson** [comment]
Make sure to use the latest code in `dev` branch. Specifically this commit: https://github.com/sourceplusplus/interface-jetbrains/pull/717/commits/92e0f2f7bae0822159909650c41c96a662bc386d

It adds better Python artifact naming.

**Comment by javamak** [comment]
I tried importing the python application to Idea editor but I am not able to place marker. I tried to configure runIde to open pycharm but failing with below error. Please suggest how I can test the plugin for Python. 

Cannot find builtin plugin 'java' for IDE: \.gradle\caches\modules-2\files-2.1\com.jetbrains.intellij.pycharm\pycharmPC\2021.3.3\ed07827b1346cfa285580cda980365a9cc00e0de\pycharmPC-2021.3.3

**Comment by BFergerson** [comment]
Forgot to mention you need some edits to make Python work. PyCharm doesn't look like it's working at the moment.

Revert your changes to `gradle.properties` and edit `SourceMarkerPlugin` from:
```kt
if (PYCHARM_PRODUCT_CODES.contains(productCode)) {
```

to:
```kt
if (true) {
```
